name: pypi
on:
  release:
    types:
      - created
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_SKIP: cp36-*
      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2
      - name: Build
        run: poetry build
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
  upload:
    runs-on: ubuntu-latest
    needs: [ build_wheels, build_sdist ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
